// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ_m0ShAyQf6f_Au67S4QLLzaEQAg8wfY',
    appId: '1:519522440551:web:b631388fd55d9d28878bc2',
    messagingSenderId: '519522440551',
    projectId: 'so-hoa-vung-trong',
    authDomain: 'so-hoa-vung-trong.firebaseapp.com',
    storageBucket: 'so-hoa-vung-trong.appspot.com',
    measurementId: 'G-PZ6E7XCSP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgT3dSGo30a4sqM8YqYQg8BtbHqwQQwnw',
    appId: '1:519522440551:android:468675bde329b576878bc2',
    messagingSenderId: '519522440551',
    projectId: 'so-hoa-vung-trong',
    storageBucket: 'so-hoa-vung-trong.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIVrpuakprMxs5_v8lHhZK7YaTkhEIyQM',
    appId: '1:519522440551:ios:a4bb9801d33932f3878bc2',
    messagingSenderId: '519522440551',
    projectId: 'so-hoa-vung-trong',
    storageBucket: 'so-hoa-vung-trong.appspot.com',
    iosBundleId: 'com.example.soHoaVungTrong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIVrpuakprMxs5_v8lHhZK7YaTkhEIyQM',
    appId: '1:519522440551:ios:a4bb9801d33932f3878bc2',
    messagingSenderId: '519522440551',
    projectId: 'so-hoa-vung-trong',
    storageBucket: 'so-hoa-vung-trong.appspot.com',
    iosBundleId: 'com.example.soHoaVungTrong',
  );
}
